### ISSUE TITLE
Misspelled at line 97 in pureblood.py

### ISSUE THREAD

**Issue by koyasushunpei** [cr4shcod3/pureblood#2]
at line 97:
elif platform.system() == 'Linux' or platform.sysmtem() == 'Darwin':

sysmtem -> system

**Comment by 1522402210** [comment]
python pureblood.py
Traceback (most recent call last):
  File "pureblood.py", line 97, in <module>
    elif platform.system() == 'Linux' or platform.sysmtem() == 'Darwin':
AttributeError: 'module' object has no attribute 'sysmtem'

**Comment by 1522402210** [comment]
@koyasushunpei  yes 
 good~

**Comment by cr4shcod3** [comment]
Done. Thanks
