### ISSUE TITLE
On Fedora 28 x 64 does not work ( Module (colorama) not installed)

### ISSUE THREAD

**Issue by xzj8b3** [cr4shcod3/pureblood#6]
[!] - Module (colorama) not installed!
[xzj8b3@x555lp pureblood]$ sudo pip install -r requirements.txt
Requirement already satisfied: colorama in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (0.3.9)
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (2.18.4)
Requirement already satisfied: python-whois in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (0.7.0)
Requirement already satisfied: dnspython in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (1.15.0)
Requirement already satisfied: bs4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (0.0.1)
Requirement already satisfied: shodan in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (1.8.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 2)) (2.5)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 2)) (1.22)
Requirement already satisfied: future in /usr/lib/python2.7/site-packages (from python-whois->-r requirements.txt (line 3)) (0.16.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/site-packages (from bs4->-r requirements.txt (line 5)) (4.6.0)
Requirement already satisfied: click in /usr/lib/python2.7/site-packages (from shodan->-r requirements.txt (line 6)) (6.7)
Requirement already satisfied: click-plugins in /usr/lib/python2.7/site-packages (from shodan->-r requirements.txt (line 6)) (1.0.3)
Requirement already satisfied: XlsxWriter in /usr/lib/python2.7/site-packages (from shodan->-r requirements.txt (line 6)) (1.0.5)

**Comment by xzj8b3** [comment]
pip install python-whois
Requirement already satisfied: python-whois in /usr/lib/python2.7/site-packages (0.7.0)
Requirement already satisfied: future in /usr/lib/python2.7/site-packages (from python-whois) (0.16.0)
- Module (python-whois) not installed!


??????????

**Comment by xzj8b3** [comment]
![schermata da 2018-07-31 15-52-58](https://user-images.githubusercontent.com/26720956/43463829-dc4a7452-94d9-11e8-9cc6-b338fddad6f1.png)

**Comment by xzj8b3** [comment]
In September as I return from holiday I try again... On Fedora 28 seems to have problems with launching various modules!!!!!

**Comment by cr4shcod3** [comment]
Please use pip3 instead pip

**Comment by cr4shcod3** [comment]
You installed the modules in python2 not in python3. I think your pip is python2 so try to use pip3 instead.

**Comment by KingDalley** [comment]
mine is also not working, same errro python-whois is not installed

**Comment by cr4shcod3** [comment]
python2 and python3 are different. pip (maybe python2 or python3) / pip2 and pip3 are different. please remember what python version you are using
