### ISSUE TITLE
FileFuzz and Directory Fuzz crashed

### ISSUE THREAD

**Issue by gearcapitan** [cr4shcod3/pureblood#9]
![imagen](https://user-images.githubusercontent.com/13740942/43988545-a93f4296-9cfd-11e8-8c2b-473754b305f6.png)
![imagen](https://user-images.githubusercontent.com/13740942/43988546-ac195eac-9cfd-11e8-8436-60d895409950.png)

**Comment by cr4shcod3** [comment]
Please analyze on how to use the tool first. It's just your error. Please provide a file for the list
